"use client";

import { Hash, ListChecks, ListTree, Loader2, NotebookPen, RefreshCw, Sparkles, type LucideIcon } from "lucide-react";
import { useState, type ReactNode } from "react";
import { api } from "@/lib/api";
import { formatTimestamp } from "@/lib/format";
import type { ActionItem, MeetingDetail } from "@/lib/types";
import { Button } from "../ui/Button";
import { useToast } from "../ui/Toast";
import { ActionItems } from "./ActionItems";

const GENERATED_BY_LABEL = {
  seed: "Sample notes",
  heuristic: "Generated by Fred · rule-based",
  llm: "Generated by Fred · Claude",
};

interface SummaryTabProps {
  meeting: MeetingDetail;
  currentTime: number;
  onSeek: (time: number) => void;
  onMeetingChange: (meeting: MeetingDetail) => void;
  onItemsChange: (change: (items: ActionItem[]) => ActionItem[]) => void;
}

/** AI notes: keywords, overview, action items and the clickable outline (chapters). */
export function SummaryTab({ meeting, currentTime, onSeek, onMeetingChange, onItemsChange }: SummaryTabProps) {
  const toast = useToast();
  const [regenerating, setRegenerating] = useState(false);
  const summary = meeting.summary;
  // The chapter that contains the current playback position.
  const currentChapter = [...meeting.chapters].reverse().find((chapter) => chapter.start_time <= currentTime);

  async function regenerate() {
    setRegenerating(true);
    try {
      onMeetingChange(await api.regenerateSummary(meeting.id));
      toast.success("AI notes regenerated from the transcript");
    } catch (error) {
      toast.error((error as Error).message);
    } finally {
      setRegenerating(false);
    }
  }

  return (
    <div className="space-y-7">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-brand-soft text-brand">
            <Sparkles size={15} />
          </span>
          <div>
            <p className="text-sm font-semibold">AI meeting notes</p>
            {summary && <p className="text-[11px] text-fg-subtle">{GENERATED_BY_LABEL[summary.generated_by]}</p>}
          </div>
        </div>
        <Button variant="secondary" size="sm" onClick={regenerate} disabled={regenerating}>
          {regenerating ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
          Regenerate
        </Button>
      </div>

      {summary && summary.keywords.length > 0 && (
        <Section icon={Hash} title="Keywords">
          <div className="flex flex-wrap gap-1.5">
            {summary.keywords.map((keyword) => (
              <span key={keyword} className="rounded-full border border-line bg-surface-hover px-2.5 py-1 text-xs font-medium">
                {keyword}
              </span>
            ))}
          </div>
        </Section>
      )}

      {summary && (
        <Section icon={NotebookPen} title="Overview">
          <ul className="space-y-2">
            {summary.overview
              .split("\n")
              .filter(Boolean)
              .map((line, index) => (
                <li key={index} className="flex gap-2.5 text-sm leading-relaxed">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />
                  {line}
                </li>
              ))}
          </ul>
        </Section>
      )}

      <Section icon={ListChecks} title="Action items">
        <ActionItems
          meetingId={meeting.id}
          items={meeting.action_items}
          people={meeting.participants.map((p) => p.name)}
          onSeek={onSeek}
          onItemsChange={onItemsChange}
        />
      </Section>

      {meeting.chapters.length > 0 && (
        <Section icon={ListTree} title="Outline">
          <ol className="space-y-1">
            {meeting.chapters.map((chapter) => (
              <li key={chapter.id}>
                <button
                  type="button"
                  onClick={() => onSeek(chapter.start_time)}
                  className={`w-full rounded-xl px-3 py-2.5 text-left transition-colors ${
                    chapter.id === currentChapter?.id ? "bg-brand-soft" : "hover:bg-surface-hover"
                  }`}
                >
                  <span className="flex items-center gap-2">
                    <span className="rounded-md bg-surface px-1.5 py-0.5 text-[11px] font-medium tabular-nums text-brand-text ring-1 ring-line">
                      {formatTimestamp(chapter.start_time)}
                    </span>
                    <span className="text-sm font-semibold">{chapter.title}</span>
                  </span>
                  {chapter.summary && <span className="mt-1 block text-sm text-fg-muted">{chapter.summary}</span>}
                </button>
              </li>
            ))}
          </ol>
        </Section>
      )}
    </div>
  );
}

function Section({ icon: Icon, title, children }: { icon: LucideIcon; title: string; children: ReactNode }) {
  return (
    <section>
      <h3 className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-fg-subtle">
        <Icon size={14} /> {title}
      </h3>
      {children}
    </section>
  );
}
